### PR TITLE
[glyphs] Convert non-metric alignment zones to metrics

### LINKED ISSUE #873: [glyphs] v2 to v3 metrics conversion looks buggy
This is acknowledged by an inline TODO:

https://github.com/googlefonts/fontc/blob/ff40153a6e77a211d55d5a7e29a5d278c87d55ca/glyphs-reader/src/font.rs#L1234

and some manual testing is backing up that suspicion.

I currently see two likely issues with the current approach:

- glyphs v2 allowed for adding custom alignment zones, so the assertion that `len(zones) <= len(metrics)` is not assured, which causes crashes on some inputs (https://github.com/googlefonts/fontc/blob/ff40153a6e77a211d55d5a7e29a5d278c87d55ca/glyphs-reader/src/font.rs#L1235-L1240)
- and it looks like at least some fonts do not use the metric ordering that we assume (for instance Alexandria (https://github.com/Gue3bara/Alexandria) has ascender, cap, x-, baseline, descender) and so we should assign them by lining up the lhs and rhs as suggested in the todo.
- there cannot be an alignment zone for 'italic angle', but we try to assign it one anway.

- In addition to this, I wonder if we should be saving any custom alignment zones so they can be set as blue zones in the `post` table? I notice that `glyphsLib` does this: https://github.com/googlefonts/glyphsLib/blob/cedaacdc2bd17e879c3332b30e567ce5bafa0f37/Lib/glyphsLib/builder/blue_values.py#L18

### PR DESCRIPTION
**Pull request by cmyr**
This is followup on #874 and should close #873.

The implementation is based on looking at what actually happens to glyph sources if they contain additional alignment zones and are converted from v2 to v3, in glyphs.

### CODE REVIEW

File: glyphs-reader/src/font.rs [hunk 1]
```diff
@@ -1256,10 +1258,48 @@ impl RawFont {
...
+        let mut new_metrics = HashMap::new();
+        for pos in non_metric_alignment_zones
+            .iter()
+            .flat_map(|master| master.iter().map(|(pos, _)| *pos))
+        {
+            if !new_metrics.contains_key(&pos) {
+                let next_zone = new_metrics.len() + 1;
+                let idx = self.metrics.len();
+                self.metrics.push(RawMetric {
+                    type_: Some(format!("zone {next_zone}")),
```
Comment (dfrg) [inline glyphs-reader/src/font.rs:1279]: If we’re going to retain these, I’d suggest capturing them into `blue_values` and `other_blues` fields as glyphslib does. I don’t think storing them as “zone _n_” has any useful meaning.

Comment (cmyr) [reply glyphs-reader/src/font.rs:1279]: as best I understand things that would happen during during the glyphs2fontir stage? All I'm trying to do here is convert v2 to v3, so that when we read glyphs sources we have a single normalized representation at the end.

Comment (dfrg) [reply glyphs-reader/src/font.rs:1279]: Ah, okay. That makes sense then. I’ll admit to not being familiar with the differences between these formats.

**Review by dfrg — APPROVED** [review]
Ignoring my misunderstanding of the purpose, code lgtm!
