### PR TITLE
[fea-rs] Correctly handle singlesub singleton class

### LINKED ISSUE #988: FEA compilation fails for contextual single sub with singleton target class
Specifically we're failing to compile [Dekko](https://github.com/EbenSorkin/Dekko) because of this.

Per the spec, if you have the following FEA,

```fea
@class1 = [a b c];
@class2 = [ g ];
sub @class1' a by @class2;
```

it is identical to just writing,

```fea
sub @class1' a by a;
```

but we're treating it as an error because the classes have a different length.

I'm not sure if we are also doing this incorrectly for non-contextual single sub statements, but it seems likely?

### PR DESCRIPTION
**Pull request by cmyr**
- fixes #988 

this will get us compiling at least one more font, which is a nice way to make the diff % go up

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]

**Comment by anthrotype** [comment]
> this will get us compiling at least one more font

@cmyr which one is that, out of curiosity?

**Comment by cmyr** [comment]
I believe it's [Dekko](https://github.com/EbenSorkin/Dekko).

File: fea-rs/src/compile/compile_ctx.rs [hunk 1]
```diff
@@ -641,6 +641,14 @@ impl<'a, F: FeatureProvider, V: VariationInfo> CompilationCtx<'a, F, V> {
                 self.error(replace.unwrap().range(), "cannot sub glyph by glyph class");
                 None
             }
+            // treat singleton class as single glyph, per the spec:
+            // "If the replacement is a singleton glyph class, then the rule
+            // will be treated identically to a format B rule":
+            // http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5a-gsub-lookuptype-1-single-substitution
```
Comment (rsheeter) [inline fea-rs/src/compile/compile_ctx.rs:647]: Optional, it would be nice to write an example as some readers [self] don't know what a format B rule is off the top of their head

File: fea-rs/test-data/compile-tests/mini-latin/good/single_sub_singleton_class.fea [hunk 2]
```diff
@@ -0,0 +1,6 @@
+feature test {
+    # "if the replacement class is a singleton glyph class, the rule is treated
+    #  as identicalto format B" (as if it were a single glyph)
```
Comment (rsheeter) [inline fea-rs/test-data/compile-tests/mini-latin/good/single_sub_singleton_class.fea:3]: nit: missing space after identical

File: fea-rs/src/compile/compile_ctx.rs (hunk 1 above)
Comment (cmyr) [reply fea-rs/src/compile/compile_ctx.rs:647]: I worry if we follow this practice in general we will end up completely reproducing the spec in our docs; if someone is curious the full section from which this is extracted is available at the provided link.
