### PR TITLE
Resolve fea includes for UFO against dir containing .ufo

### LINKED ISSUE #296: Included feature files not found
1. Try and compile https://github.com/madig/FirerSans/blob/main/sources/FiraSans.designspace
2. :fire: 

```
2023-05-23T21:03:02.584914Z: ThreadId(1): ERROR: Be(Features) failed Be(FeaCompileError(ParseFail(DiagnosticSet { messages: [Diagnostic { message: Message { text: "Failed to load source at 'family.fea': 'No such file or directory (os error 2)'", file: FileId(2), span: Span { start: 8, end: 18 } }, level: Error }], tree: "ParseTree" })))
Error: TasksFailed([(Be(Features), "Fea compilation failure")])
```

The default source just includes a shared family.fea: https://github.com/madig/FirerSans/blob/main/sources/FiraSans-Regular.ufo/features.fea -> https://github.com/madig/FirerSans/blob/main/sources/family.fea

The include path logic is explained in https://github.com/googlefonts/ufo2ft/blob/0d2688cd847d003b41104534d16973f72ef26c40/Lib/ufo2ft/featureCompiler.py#L47-L51.

### PR DESCRIPTION
**Pull request by rsheeter**
First crack at resolving includes. For the purposes of incremental compilation all fea files in the .designspace dir will be considered for feature file change. An include pointed outside the .designspace dir won't be detected as changed when attempting incremental compile.

Fixes #296. After this change I can compile https://github.com/madig/FirerSans w/o error. I make no claim that the font will actually _work_ ofc.

### CODE REVIEW

File: fontbe/src/features.rs [hunk 1]
```diff
@@ -73,19 +73,26 @@ impl FeatureWork {
...
+            } => {
+                let mut compiler = Compiler::new(OsString::from(fea_file), &glyph_order);
+                if let Some(include_dir) = include_dir {
+                    compiler = compiler.with_project_root(include_dir)
+                }
+                compiler
+            }
+            Features::Memory(fea_content) => {
+                let root = OsString::new();
+                Compiler::new(root.clone(), &glyph_order).with_resolver(InMemoryResolver {
```
Comment (anthrotype) [inline fontbe/src/features.rs:89]: `include_dir` isn't used for in-memory compilation, does it mean we only properly support resolving external .fea includes when emitting IR and thus compiling features from a file?

File: ufo2fontir/src/source.rs [hunk 2]
```diff
@@ -836,7 +858,11 @@ impl Work<Context, WorkError> for FeatureWork {
         }
 
         if !fea_files.is_empty() {
-            context.set_features(Features::from_file(&fea_files[0]));
+            let designspace_dir = self.designspace_file.parent().unwrap();
+            context.set_features(Features::from_file(
+                fea_files[0].clone(),
+                Some(designspace_dir.to_path_buf()),
```
Comment (anthrotype) [inline ufo2fontir/src/source.rs:864]: no, it's not "relative to the directory of the .designspace", it's relative to the directory of the UFO. The designspace spec doesn't say anything about features.fea, it's the UFO spec that mandates that:
https://unifiedfontobject.org/versions/ufo3/features.fea/

it happens to work with FirerSans because in that particular case the source UFOs which contain features.fea with include statements happen to be in the same directory as the .designspace file that glues them together, but they may well be in a different sub-directory

Comment (rsheeter) [reply ufo2fontir/src/source.rs:864]: Note to self: directory of the UFO means the directory containing it, not the actual blah.ufo/ directory

File: fontbe/src/features.rs (hunk 1 above)
Comment (rsheeter) [reply fontbe/src/features.rs:89]: I'll double-check and add a test; it should work.

File: resources/testdata/fea_include.designspace [hunk 3]
```diff
@@ -0,0 +1,35 @@
+<?xml version='1.0' encoding='UTF-8'?>
+<!-- Derived from Noto Sans Adlam -->
+<designspace format="4.1">
+  <axes>
+    <axis tag="wght" name="Weight" minimum="400" maximum="700" default="400"/>
+  </axes>
+  <sources>
+    <source filename="FeaInc-Regular.ufo" name="Fea Inc Regular" familyname="Fea Inc" stylename="Regular">
```
[the remark this answers is not in the document]
Comment (rsheeter) [reply resources/testdata/fea_include.designspace:8]: Ty, will fix.

**Review by anthrotype — APPROVED** [review]
LGTM provided we change it relative to UFO path and verify this works for in-memory compilation as well

File: ufo2fontir/src/source.rs (hunk 2 above)
Comment (rsheeter) [reply ufo2fontir/src/source.rs:864]: I will modify my test files to expose the bug & fix.

File: fontbe/src/features.rs (hunk 1 above)
Comment (rsheeter) [reply fontbe/src/features.rs:90]: (in memory should be when the source is in memory, not just when emit ir is off)

Comment (anthrotype) [reply fontbe/src/features.rs:90]: oh, like when compiling off .glyphs source (which embeds a features string in its single file source) as opposed to designspace+UFO where features.fea are distinct files?

**Comment by rsheeter** [comment]
> verify this works for in-memory compilation as well

Added a test with IR turned off
